{% set data = load_setup_py_data() %}

package:
  name: thermohw
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  noarch: python
  entry_points:
    - convert_thermo_hw = thermohw.convert_thermo_hw:main
    - convert_thermo_exam = thermohw.convert_thermo_exam:main

requirements:
  build:
    - python
    - setuptools
    - pip

  run:
    - python >=3.6,<4.0
    - nbconvert >=5.3,<6.0
    - traitlets >=4.3,<5.0
    - pdfrw >=0.4,<0.5
    - pandocfilters >=1.4,<2.0

test:
  imports:
    - thermohw

  requires:
    - pytest >=3.2.0

  commands:
    - pytest -vv --pyargs thermohw
    - convert_thermo_hw --help

about:
  home: {{ data['url'] }}
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD

  summary: {{ data['description'] }}
  description: |
    Homework assignment converter from Jupyter Notebooks to PDF

    This package installs a CLI script to convert Jupyter Notebook homework
    assignments to PDF (with and without solutions) and a set of Notebooks
    (with and without solutions).
  doc_url: https://bryanwweber.github.io/thermohw
  dev_url: {{ data['url'] }}
