{% set data = load_setup_py_data() %}

package:
  name: thermohw
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python
  entry_points:
    - convert_thermo_hw = thermohw.convert_thermo_hw:main

requirements:
  build:
    - python >=3.5
    - setuptools

  run:
    - python
    - nbconvert
    - traitlets
    - jupyter_contrib_nbextensions
    - pdfrw

test:
  imports:
    - thermohw

  # requires:
  #   - pytest >=3.2.0
  #   - pytest-cov >=2.3.1

  commands:
    # - pytest -vv --pyargs thermohw
    - convert_thermo_hw --help

about:
  home: data['url']
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD

  summary: data['description']
  description: data['long_description']
  doc_url: https://bryanwweber.github.io/thermohw
  dev_url: data['url']
